project:
  type: website

website:
  title: "HAN BK Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hutten.qmd
        text: Hutten

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true