project:
  type: website
  output-dir: site

website:
  title: "HAN BK Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: casus.qmd
        text: Casus

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true